# Generated by Django 3.0 on 2022-12-21 05:48

# Django
from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=25, verbose_name='lastname')),
                ('phone_number', models.IntegerField(verbose_name='phone number')),
                ('apartment_number', models.IntegerField(verbose_name='apartment number')),
                ('has_paid_taxes', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('lastname',),
            },
        ),
    ]
