# Generated by Django 4.1.4 on 2022-12-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_auto_20221221_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tempmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
